// backend/src/workers/bulkDownload.worker.js
'use strict';

const { Worker }                = require('bullmq');
const { pool }                  = require('../config/database');
const { createRedisClient }     = require('../config/redis');
const { QUEUE_NAMES }           = require('./queue');
const { runPythonScript }       = require('../utils/ipcRunner');
const { sanitizePAN }           = require('../utils/panSanitizer');
const { AUDIT_ACTIONS }         = require('../constants/auditActions');
const { insertAuditLog }        = require('../services/audit.service');
const { sendFailedAlert }       = require('../services/email.service');
const { r2Paths }               = require('../utils/r2Paths');
const { formatDateForFilename } = require('../utils/istTime');
const { getNextFileSequence } = require('../utils/fileSequence');
const { todayIST }            = require('../utils/istTime');


function createBulkDownloadWorker() {
  const worker = new Worker(
    QUEUE_NAMES.BULK_DOWNLOAD,
    async (job) => {
      const { batchId, targetDate, batchSequence, requestId } = job.data;

      console.log(JSON.stringify({
        level:     'INFO',
        timestamp: new Date().toISOString(),
        worker:    'bulkDownload',
        batchId,
        message:   `Starting bulk download for ${targetDate}`,
      }));

      try {
        // ── Fetch required keys from DB ────────────────────────
        const batchResult = await pool.query(
          `SELECT response_file_key, pan_dob_r2_key, batch_sequence
           FROM ckyc_batches WHERE id = $1`,
          [batchId]
        );

        if (batchResult.rows.length === 0) {
          throw new Error(`Batch ${batchId} not found`);
        }

        const { response_file_key, pan_dob_r2_key } = batchResult.rows[0];

        if (!response_file_key) {
          throw new Error(`No response_file_key found for batch ${batchId}`);
        }

        if (!pan_dob_r2_key) {
          throw new Error(
            `No pan_dob_r2_key found for batch ${batchId}. ` +
            `This is generated by search_generator.py — ` +
            `ensure the search generation step completed successfully.`
          );
        }

        // ── Build R2 output key ────────────────────────────────
        const fileSeq     = await getNextFileSequence('download');
        const seqStr      = String(fileSeq).padStart(5, '0');
        const today       = todayIST();
        const dateStr     = formatDateForFilename(today);
        const filename    = `IN3860_IT_${dateStr}_V1.3_D${seqStr}.txt`;
        
        // Store in targetDate's folder, filename has today's date
        const r2OutputKey = r2Paths.downloadFile(targetDate, filename);
        
        // ── Run download_generator.py ──────────────────────────
        const result = await runPythonScript(
          'download_generator.py',
          {
            target_date:      targetDate,
            batch_sequence:   batchSequence,
            response_r2_key:  response_file_key,
            pan_dob_r2_key:   pan_dob_r2_key,
            r2_output_key:    r2OutputKey,
          },
          requestId
        );

        // ── Update download_file_key ───────────────────────────
        await pool.query(
          `UPDATE ckyc_batches
           SET download_file_key = $2
           WHERE id = $1`,
          [batchId, result.r2_key_written || r2OutputKey]
        );

        // ── Try to set COMPLETED ───────────────────────────────
        await _trySetCompleted(batchId);

        await insertAuditLog({
          action:   AUDIT_ACTIONS.BATCH_GENERATED,
          batchId,
          metadata: {
            target_date:    targetDate,
            record_count:   result.record_count || 0,
            r2_key:         result.r2_key_written || r2OutputKey,
            stage:          'bulk_download',
          },
        });

        console.log(JSON.stringify({
          level:        'INFO',
          timestamp:    new Date().toISOString(),
          worker:       'bulkDownload',
          batchId,
          message:      'Bulk download complete',
          record_count: result.record_count || 0,
        }));

      } catch (err) {
        const sanitizedError = sanitizePAN(err.message || 'Unknown error', 500);

        await pool.query(
          `UPDATE ckyc_batches
           SET status        = 'FAILED',
               error_message = $2
           WHERE id = $1`,
          [batchId, sanitizedError]
        );

        await insertAuditLog({
          action:   AUDIT_ACTIONS.BATCH_FAILED,
          batchId,
          metadata: {
            target_date: targetDate,
            error:       sanitizedError,
            stage:       'bulk_download',
          },
        });

        sendFailedAlert({
          targetDate,
          batchSequence,
          stage:        'bulk_download',
          errorMessage: sanitizedError,
          batchId,
        }).catch(() => {});

        throw err;
      }
    },
    {
      connection:      createRedisClient(),
      concurrency:     1,          // (or 2 — keep as-is per worker)
      stalledInterval: 300000,     // check stalled jobs every 5 min
      maxStalledCount: 1,
      drainDelay:      1,          // 0 = use blocking pop (push-based, no polling)
    }
      );

  worker.on('failed', (job, err) => {
    console.error(JSON.stringify({
      level:   'ERROR',
      worker:  'bulkDownload',
      jobId:   job?.id,
      message: `Job permanently failed: ${sanitizePAN(err.message)}`,
    }));
  });

  return worker;
}

async function _trySetCompleted(batchId) {
  const result = await pool.query(
    `UPDATE ckyc_batches
     SET status = 'COMPLETED'
     WHERE id                = $1
       AND download_file_key IS NOT NULL
       AND upload_file_key   IS NOT NULL
       AND status            = 'PROCESSING_RESPONSE'
     RETURNING id`,
    [batchId]
  );

  if (result.rows.length > 0) {
    console.log(JSON.stringify({
      level:     'INFO',
      timestamp: new Date().toISOString(),
      message:   `Batch ${batchId} → COMPLETED`,
    }));
  }
}

module.exports = { createBulkDownloadWorker, _trySetCompleted };