// backend/src/utils/r2Paths.js
'use strict';

// ── Date format helper ────────────────────────────────────────────
// PostgreSQL DATE comes back as a JS Date object or 'YYYY-MM-DD' string.
// R2 paths use 'DD-MM-YYYY' format per the PRD spec.
// This function handles both input formats safely.
function formatDateForPath(date) {
  let d;

  if (date instanceof Date) {
    // JS Date — extract parts in UTC to avoid timezone shift
    const day   = String(date.getUTCDate()).padStart(2, '0');
    const month = String(date.getUTCMonth() + 1).padStart(2, '0');
    const year  = date.getUTCFullYear();
    return `${day}-${month}-${year}`;
  }

  if (typeof date === 'string') {
    // Handle 'YYYY-MM-DD' format from PostgreSQL
    if (/^\d{4}-\d{2}-\d{2}$/.test(date)) {
      const [year, month, day] = date.split('-');
      return `${day}-${month}-${year}`;
    }
    // Already in 'DD-MM-YYYY' format
    if (/^\d{2}-\d{2}-\d{4}$/.test(date)) {
      return date;
    }
  }

  throw new Error(
    `r2Paths: Cannot format date "${date}". ` +
    `Expected a Date object, 'YYYY-MM-DD', or 'DD-MM-YYYY' string.`
  );
}

// ── R2 path builders ──────────────────────────────────────────────
// Every R2 object key in the entire application is built by one
// of these functions. No path is ever constructed inline.
//
// Structure: ckyc/{dd-mm-yyyy}/{type}/{filename}
//
// The date segment always uses the batch's target_date —
// never the current date at time of operation.

const r2Paths = {

  // Search file: generated by search_generator.py
  // e.g. ckyc/09-03-2026/search/IN3860_09032026_V1.1_S00016.txt
  searchFile(targetDate, filename) {
    return `ckyc/${formatDateForPath(targetDate)}/search/${filename}`;
  },

  // Response file: uploaded by browser directly
  // e.g. ckyc/09-03-2026/response/IN3860_09032026_V1.1_S00016_Res.txt
  responseFile(targetDate, filename) {
    return `ckyc/${formatDateForPath(targetDate)}/response/${filename}`;
  },

  // Download file: generated by bulk_download.py
  // e.g. ckyc/09-03-2026/download/IN3860_09032026_V1.1_S00016.txt
  downloadFile(targetDate, filename) {
    return `ckyc/${formatDateForPath(targetDate)}/download/${filename}`;
  },

  // Upload ZIP: generated by upload_generator.py
  // e.g. ckyc/09-03-2026/upload/IN3860_IT_09032026_V1.3_IRA010431_U10001.zip
  uploadFile(targetDate, filename) {
    return `ckyc/${formatDateForPath(targetDate)}/upload/${filename}`;
  },

  // Returns the folder prefix for a given date and type.
  // Useful for listing all files of a type for a given date.
  prefix(targetDate, type) {
    const validTypes = ['search', 'response', 'download', 'upload'];
    if (!validTypes.includes(type)) {
      throw new Error(`r2Paths.prefix: invalid type "${type}"`);
    }
    return `ckyc/${formatDateForPath(targetDate)}/${type}/`;
  },
};

// ── Key validator ─────────────────────────────────────────────────
// Verifies a key looks structurally correct before R2 operations.
// Catches bugs like null dates creating 'ckyc/undefined/search/...'
function validateKey(key) {
  if (!key || typeof key !== 'string') {
    throw new Error(`r2Paths: Key must be a non-empty string, got: ${key}`);
  }
  if (!key.startsWith('ckyc/')) {
    throw new Error(`r2Paths: Key must start with 'ckyc/', got: "${key}"`);
  }
  if (key.includes('undefined') || key.includes('null')) {
    throw new Error(`r2Paths: Key contains 'undefined' or 'null': "${key}"`);
  }
  return true;
}

module.exports = { r2Paths, formatDateForPath, validateKey };